-- ============================================================
-- Supabase schema index
-- ============================================================
-- File SQL lon da duoc tach thanh nhieu file nho trong:
--   backend/scripts/supabase/schema/
--
-- Thu tu chay de setup schema:
--   01_profiles.sql
--   02_events.sql
--   03_registrations.sql
--   04_event_feedback.sql
--   05_rls.sql
--   06_updated_at_triggers.sql
--   07_registered_count.sql
--   08_handle_new_user.sql
--
-- Tuy chon:
--   00_block_signup.sql
--
-- Huong dan:
-- - Mo tung file trong thu muc schema/ va chay theo thu tu tren trong Supabase SQL Editor.
-- - File nay chi giu vai tro muc luc de tranh duplicate SQL o hai noi.
-- - Xem them: backend/scripts/supabase/schema/README.md
